name: Publish blog updates
on: 
  push:
    branches: 
      - master

env: # TODO use new env names needed by s3-sync-action
  AWS_REGION: ${{secrets.AWS_REGION}}
  AWS_ACCESS_KEY_ID: ${{secrets.AWS_ACCESS_KEY_ID}}
  AWS_SECRET_ACCESS_KEY: ${{secrets.AWS_SECRET_ACCESS_KEY}}
  AWS_S3_BUCKET: ${{secrets.AWS_BUCKET_NAME}}
  SOURCE_DIR: ${{secrets.HQ_DIST_SITE_FOLDER}}
  AWS_CF_DIST_ID: ${{secrets.AWS_CF_DIST_ID}}
  
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout 
      uses: actions/checkout@v3

    - name: Prepare Node.js
      uses: actions/setup-node@v3
        
    - name: Build static site
      run: |
        npm install
        npm run build
    
    - name: S3 upload
      uses: jakejarvis/s3-sync-action@v0.5.1
      with:
        args: --follow-symlinks --delete

    - name: Clear cloudfront cache
      run: |
        aws cloudfront create-invalidation --distribution-id ${{ env.AWS_CF_DIST_ID }} --paths "/*"
