name: Publish new blog version
on: 
  push:
    branches: 
      - master
jobs:
  build:
    env:
      TOKEN: ${{secrets.TOKEN}}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]
    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: npm install and publish
      run: |
        npm install
        npm run release:ci
